### ISSUE TITLE
Adding the segment package makes dbt ignore custom schemas and sends all models to default schema

### ISSUE THREAD

**Issue by Plamen8780** [dbt-labs/segment#61]
### Describe the bug
Adding the segment package makes dbt ignore custom schemas and sends all models to default schema

### Steps to reproduce
This is the code that we've added in dbt_project.yml:
```
vars:
  segment:
    #where the raw data to be used in the package lives
    segment_page_views_table: "{{ ref('segment_pageview') }}"
    #sessionization inactivity cutoff where there is a gap in pageview times. If it exceeds this number of seconds it will start a new session - in this case 30 mins * 60 seconds
    segment_inactivity_cutoff: 30 * 60

models:
  segment:
    +schema: chnl_segment_sessions
    +tags: 'daily'
```

We are using get_custom_schema.sql and generate_schema_name_for_env.sql macros to specify custom schemas.

Before adding the segment package the custom schemas worked fine.

### Expected results
We would expect the models to be created in the custom schemas and the new segment models to be created in schema chnl_segment_sessions

### Actual results
All models are created in the dbt schema, despite having a custom schema configured

### System information
**The contents of your `packages.yml` file:**
```
packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.6.2
  - package: fishtown-analytics/segment
    version: 0.5.1
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.18.0
   latest version: 0.18.1

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 0.18.0
  - snowflake: 0.18.0
  - redshift: 0.18.0
  - postgres: 0.18.0
```

**The operating system you're using:**
Docker container with python:3.7

**The output of `python --version`:**
Python 3.7.7
