### ISSUE TITLE
Duplicating session_number in incremental materializations

### ISSUE THREAD

**Issue by rjh336** [dbt-labs/segment#80]
### Describe the bug
There was an issue introduced in #73 in the updated `segment_web_sessions` model [here](https://github.com/dbt-labs/segment/blob/fbf5c49914d0908e5e5bb846a525939f477045ca/models/sessionization/segment_web_sessions.sql#L41) where the comparison operator was flipped in the `agg` CTE for incremental materializations. The result is that `session_number` starts to get repeated for newly added sessions which we do not want.

### Steps to reproduce
1. dbt run to MERGE to existing tables
2. check segment_web_sessions output and you will see new web sessions start counting from 1 instead of the last known session_number for each blended user ID

### Expected results
session_number is incremented over a user's sessions

### Actual results
duplicate session numbers for each user on incremental runs

### System information
**The contents of your `packages.yml` file:**
```
packages:
  - package: dbt-labs/segment
    version: 0.8.0
  - package: dbt-labs/audit_helper
    version: 0.5.0
  - package: dbt-labs/stitch_utils
    version: 0.4.1
  - package: dbt-labs/dbt_utils
    version: 0.8.0
  - package: dbt-labs/dbt_external_tables
    version: 0.8.0
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 1.0.3
   latest version: 1.0.3

Up to date!

Plugins:
  - bigquery: 1.0.0 - Up to date!
  - snowflake: 1.0.0 - Up to date!
  - redshift: 1.0.0 - Up to date!
  - postgres: 1.0.3 - Up to date!
```

**The operating system you're using:** MacOS

**The output of `python --version`:** Python 3.8.11
